Repository ember-learn/ember-cli-addon-docs, pull requests merged in 2021-11, with the labels that each got.

#978 Fixes broken deployment with ember-auto-import@2
  blueprints/ember-cli-addon-docs/index.js
Labels: bug

#981 Fix typo at navigation
  tests/dummy/app/templates/docs.hbs
Labels: documentation

#1006 chore(deps): drop ember-href-to
  addon/services/docs-routes.js
  package.json
  yarn.lock
Labels: internal
