Repository ember-learn/ember-cli-addon-docs, pull requests merged in 2021-09, with the labels that each got.

#923 Bump some deps, update Ember to 3.28
  .eslintignore
  .eslintrc.js
  .github/workflows/ci-cd.yml
  .npmignore
  .prettierrc.js
  README.md
  addon/components/api/x-component/template.hbs
  addon/components/api/x-import-path/component.js
  addon/components/api/x-section/template.hbs
  addon/components/api/x-sections/component.js
  addon/components/docs-code-highlight/component.js
  addon/components/docs-demo/component.js
  addon/components/docs-demo/x-example/component.js
  addon/components/docs-header/search-result/template.hbs
  addon/components/docs-header/version-selector/component.js
  addon/components/docs-link/component.js
  addon/components/docs-logo/component.js
  addon/components/docs-snippet/component.js
  addon/components/docs-snippet/template.hbs
  addon/components/docs-viewer/x-autogenerated-api-docs/component.js
  addon/components/docs-viewer/x-autogenerated-api-docs/module-nav/component.js
  addon/components/docs-viewer/x-autogenerated-api-docs/module-nav/template.hbs
  addon/components/docs-viewer/x-current-page-index/component.js
  addon/components/docs-viewer/x-main/component.js
  addon/components/docs-viewer/x-main/template.hbs
  addon/components/docs-viewer/x-nav-list/component.js
  addon/components/modal-dialog/component.js
  app/templates/docs/api/item.hbs
  config/ember-try.js
  ember-cli-build.js
  package.json
  test-apps/new-addon/package.json
  test-apps/new-addon/tests/dummy/app/templates/index.md
  test-apps/new-addon/tests/dummy/app/templates/route-using-compile-markdown.hbs
  test-apps/new-addon/tests/index.html
  test-apps/new-addon/tests/test-helper.js
  tests/acceptance/sandbox/api/guides-test.js
  tests/acceptance/search-test.js
  tests/acceptance/version-selector-test.js
  tests/dummy/app/components/index/index-content.md
  tests/dummy/app/pods/docs/components/docs-snippet/template.md
  tests/dummy/app/pods/sandbox/api/item/template.hbs
  tests/dummy/app/pods/sandbox/template.hbs
  tests/dummy/app/templates/docs/index.md
  tests/dummy/app/templates/docs/patterns.md
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/targets.js
  tests/index.html
  tests/integration/helpers/type-signature-test.js
  tests/test-helper.js
  yarn.lock
Labels: enhancement

#921 Resolve issue with sidebar showing incorrectly on mobile
  addon/components/docs-viewer/x-nav/component.js
  addon/components/docs-viewer/x-nav/template.hbs
  addon/initializers/inject-media.js
  app/initializers/inject-media.js
  package.json
  yarn.lock
Labels: bug

#932 Ember 4 support
  addon/routes/docs/api/item.js
  addon/services/project-version.js
  package.json
  tests/dummy/app/pods/sandbox/route.js
  tests/helpers/destroy-app.js
  tests/helpers/module-for-acceptance.js
  tests/helpers/start-app.js
  yarn.lock
Labels: enhancement

#933 Require ember-auto-import 2
  .github/workflows/ci-cd.yml
  package.json
  test-apps/new-addon/package.json
  yarn.lock
Labels: breaking

#939 fix: move @glimmer/component and @glimmer/tracking in dependencies
  package.json
Labels: bug

#940 fix: yarn.lock with ember-modal-dialog commit
  yarn.lock
Labels: bug

#941 build: remove some unused deps / devDeps
  package.json
  yarn.lock
Labels: dependencies
