Repository ember-learn/ember-cli-addon-docs, pull requests merged in 2021-12, with the labels that each got.

#1017 Fix typo in addon status callout
  README.md
Labels: documentation

#1010 Update linting, bump deps
  .eslintrc.js
  addon/components/docs-header/search-results/index.js
  babel.config.js
  package.json
  sandbox/.eslintrc.js
  yarn.lock
Labels: internal

#1031 Add babel.config.js to .npmignore
  .eslintrc.js
  .npmignore
  babel.config.js
  package.json
  yarn.lock
Labels: internal

#1018 Bump ember-keyboard from 6.0.3 to 7.0.0-beta.0
  package.json
  tests/dummy/config/environment.js
  yarn.lock
Labels: dependencies

#1019 Set default CI config blueprints to run all builds
  .github/workflows/ci-cd.yml
Labels: internal

#1032 Bump eslint-plugin-qunit from 6.2.0 to 7.1.0 and fix lint errors
  package.json
  tests/acceptance/docs-route-test.js
  tests/acceptance/sandbox/api/components-test.js
  tests/acceptance/sandbox/api/guides-test.js
  tests/acceptance/sandbox/api/helpers-test.js
  tests/acceptance/search-test.js
  tests/integration/helpers/type-signature-test.js
  tests/unit/utils/compile-markdown-test.js
  yarn.lock
Labels: dependencies

#1044 Bump some deps
  package.json
  yarn.lock
Labels: dependencies

#1045 Fix typo in <DocsKeyboardShortcuts /> component
  addon/components/docs-keyboard-shortcuts/index.hbs
Labels: bug
