Repository ember-learn/ember-cli-addon-docs, pull requests merged in 2022-02, with the labels that each got.

#1108 Fix no implicit this deprecation in docs-demo component
  addon/components/docs-demo/index.hbs
Labels: bug

#1116 update ember-data related syntax
  addon/adapters/-addon-docs.js
  addon/adapters/class.js
  addon/adapters/component.js
  addon/adapters/module.js
  addon/adapters/project.js
  addon/models/class.js
  addon/models/component.js
  addon/models/module.js
  addon/models/project.js
  addon/serializers/-addon-docs.js
  package.json
  tests/dummy/mirage/config.js
  tests/dummy/mirage/serializers/application.js
  yarn.lock
Labels: internal

#1120 Update to glimmer components
  addon/components/docs-code-highlight/index.hbs
  addon/components/docs-code-highlight/index.js
  addon/components/docs-demo/index.hbs
  addon/components/docs-demo/index.js
  addon/components/docs-demo/x-example/index.hbs
  addon/components/docs-demo/x-example/index.js
  addon/components/docs-demo/x-snippet.js
  addon/components/docs-snippet/index.hbs
  addon/components/docs-snippet/index.js
  index.js
  package.json
  test-apps/new-addon/tests/acceptance/snippets-test.js
  test-apps/new-addon/tests/dummy/app/templates/snippets.hbs
  tests/dummy/app/controllers/docs/components/docs-demo.js
  tests/dummy/app/pods/docs/components/docs-logo/demo1/template.hbs
  tests/dummy/app/pods/docs/components/docs-logo/demo2/template.hbs
  tests/dummy/app/pods/docs/components/docs-logo/demo3/template.hbs
  tests/dummy/app/router.js
  tests/dummy/app/templates/docs.hbs
  tests/dummy/app/templates/docs/build-options.md
  tests/dummy/app/templates/docs/components/docs-demo.md
  tests/dummy/app/templates/docs/components/docs-header.md
  tests/dummy/app/templates/docs/components/docs-hero.md
  tests/dummy/app/templates/docs/components/docs-snippet.md
  tests/dummy/app/templates/docs/components/docs-viewer.md
  tests/dummy/app/templates/docs/quickstart.md
  tests/dummy/app/templates/docs/upgrade-to-5.md
  yarn.lock
Labels: breaking

#1123 update docs hero docs
  test-apps/new-addon/tests/dummy/app/templates/index.md
  tests/dummy/app/templates/docs/components/docs-hero.md
  tests/dummy/app/templates/index.hbs
Labels: documentation

#1124 update docs-keyboard-shortcuts
  addon/components/docs-keyboard-shortcuts/index.js
  package.json
  tests/dummy/app/templates/application.hbs
  yarn.lock
Labels: enhancement

#1125 update docs-logo component
  addon/components/docs-logo/index.hbs
  addon/components/docs-logo/index.js
  tests/dummy/app/pods/docs/components/docs-logo/demo1/template.hbs
  tests/dummy/app/pods/docs/components/docs-logo/demo2/template.hbs
  tests/dummy/app/pods/docs/components/docs-logo/demo3/template.hbs
  tests/dummy/app/pods/docs/components/docs-logo/template.md
  tests/dummy/app/templates/docs/upgrade-to-5.md
Labels: enhancement

#1127 update api components
  addon/components/api/x-class/index.js
  addon/components/api/x-component/index.hbs
  addon/components/api/x-component/index.js
  addon/components/api/x-section/index.js
  addon/components/api/x-toggles.hbs
  addon/router.js
  addon/utils/compile-markdown.js
  addon/utils/computed.js
  sandbox/app/components/yuidoc-component.js
  test-apps/new-addon/addon/components/some-component.js
  tests/dummy/app/templates/docs/components/docs-snippet.md
Labels: internal

#1126 delete docs-svg-icon component
  addon/components/docs-svg-icon/index.hbs
  addon/components/docs-svg-icon/index.js
  app/components/docs-svg-icon.js
Labels: breaking

#1130 update docs-link
  addon/components/docs-link.js
  addon/components/docs-link/index.hbs
  addon/components/docs-link/index.js
  addon/models/component.js
  addon/models/module.js
  package.json
  test-apps/new-addon/package.json
  test-apps/new-addon/tests/dummy/config/optional-features.json
  tests/dummy/app/templates/docs/patterns.md
  tests/dummy/app/templates/docs/quickstart.md
  tests/dummy/app/templates/docs/upgrade-to-5.md
  yarn.lock
Labels: breaking

#955 Ember and dep updates
  .eslintignore
  .eslintrc.js
  .github/workflows/ci-cd.yml
  .gitignore
  .npmignore
  .prettierignore
  README.md
  addon/services/project-version.js
  config/ember-try.js
  index.js
  package.json
  test-apps/new-addon/package.json
  test-apps/new-addon/tests/acceptance/snippets-test.js
  test-apps/new-addon/tests/dummy/app/templates/components/my-awesome-thing.hbs
  tests/dummy/app/components/my-awesome-thing.hbs
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/dummy/mirage/config.js
  yarn.lock
Labels: internal

#1133 update markdown rendering approach
  addon/components/docs-code-highlight/index.js
  addon/components/docs-demo/index.js
  addon/utils/compile-markdown.js
  package.json
  tests-node/unit/utils/compile-markdown-test.js
  tests/dummy/app/templates/docs/components/docs-demo.md
  tests/dummy/app/templates/docs/quickstart.md
  tests/unit/utils/compile-markdown-test.js
  yarn.lock
Labels: breaking

#1134 update docs viewer
  addon/components/api/x-import-path.hbs
  addon/components/api/x-meta-panel/header.hbs
  addon/components/api/x-meta-panel/index.hbs
  addon/components/api/x-module/index.hbs
  addon/components/api/x-section/index.hbs
  addon/components/api/x-toggles.hbs
  addon/components/docs-demo/index.hbs
  addon/components/docs-demo/index.js
  addon/components/docs-header/search-box/index.hbs
  addon/components/docs-keyboard-shortcuts/index.hbs
  addon/components/docs-viewer/index.hbs
  addon/components/docs-viewer/index.js
  addon/components/docs-viewer/x-autogenerated-api-docs/index.hbs
  addon/components/docs-viewer/x-autogenerated-api-docs/index.js
  addon/components/docs-viewer/x-autogenerated-api-docs/module-nav/index.hbs
  addon/components/docs-viewer/x-autogenerated-api-docs/module-nav/index.js
  addon/components/docs-viewer/x-current-page-index/index.hbs
  addon/components/docs-viewer/x-current-page-index/index.js
  addon/components/docs-viewer/x-main/index.hbs
  addon/components/docs-viewer/x-main/index.js
  addon/components/docs-viewer/x-nav-item/index.hbs
  addon/components/docs-viewer/x-nav-item/index.js
  addon/components/docs-viewer/x-nav-list/index.hbs
  addon/components/docs-viewer/x-nav-list/index.js
  addon/components/docs-viewer/x-nav/index.hbs
  addon/components/docs-viewer/x-nav/index.js
  addon/components/docs-viewer/x-section/index.hbs
  addon/components/docs-viewer/x-section/index.js
  addon/services/docs-routes.js
  blueprints/docs-page/index.js
  sandbox/app/components/simple-list/component.js
  sandbox/app/components/simple-list/item/component.js
  sandbox/app/components/yuidoc-component.js
  test-apps/new-addon/tests/dummy/app/templates/docs.hbs
  tests-node/fixtures/blueprints/docs-subnav.hbs
  tests-node/fixtures/blueprints/docs.hbs
  tests-node/unit/blueprints/docs-page-test.js
  tests/dummy/app/pods/sandbox/template.hbs
  tests/dummy/app/router.js
  tests/dummy/app/templates/docs.hbs
  tests/dummy/app/templates/docs/components/docs-demo.md
  tests/dummy/app/templates/docs/upgrade-to-5.md
Labels: breaking

#1135 Remove ember-decorators and ember-component-css
  package.json
  tests/dummy/app/pods/docs/components/docs-logo/demo1/styles.scss
  tests/dummy/app/pods/docs/components/docs-logo/demo1/template.hbs
  tests/dummy/app/pods/docs/components/docs-logo/demo2/styles.scss
  tests/dummy/app/pods/docs/components/docs-logo/demo2/template.hbs
  tests/dummy/app/pods/docs/components/docs-logo/demo3/styles.scss
  tests/dummy/app/pods/docs/components/docs-logo/demo3/template.hbs
  tests/dummy/app/pods/docs/components/docs-logo/template.md
  tests/dummy/app/styles/app.scss
  tests/dummy/app/templates/docs/components/docs-logo.md
  yarn.lock
Labels: internal

#1137 fix(config): use runtime config instead of embroider generated one
  addon/adapters/-addon-docs.js
Labels: bug
