Repository ember-learn/ember-cli-addon-docs, pull requests merged in 2023-12, with the labels that each got.

#1517 fix compatibility with ember-data 5
  .github/workflows/ci-cd.yml
  addon/models/class.js
  addon/models/module.js
  addon/models/project.js
  tests/dummy/config/ember-try.js
Labels: bug

#1519 Bump some deps
  package.json
  yarn.lock
Labels: dependencies

#1520 ember-cli update to 5.5.0, require node 18+
  .ember-cli
  .github/workflows/ci-cd.yml
  CONTRIBUTING.md
  README.md
  addon/-private/config.js
  package.json
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/helpers/index.js
  yarn.lock
Labels: breaking

#1525 Bump marked and hosted-git-info
  .github/workflows/ci-cd.yml
  addon/utils/compile-markdown.js
  package.json
  yarn.lock
Labels: dependencies
