Repository ember-learn/ember-cli-addon-docs, pull requests merged in 2024-12, with the labels that each got.

#1617 Switch default primary branch to `main`, update docs from Travis to GitHub Actions
  .github/workflows/ci-cd.yml
  config/deploy.js
  lib/config.js
  package.json
  tests/acceptance/sandbox/api/components-test.js
  tests/acceptance/version-selector-test.js
  tests/dummy/app/templates/docs/deploying.md
  tests/dummy/app/templates/docs/patterns.md
  tests/dummy/app/templates/docs/quickstart.md
  tests/dummy/mirage/config.js
Labels: breaking

#1626 Update release-it and various deps
  package.json
  pnpm-lock.yaml
Labels: dependencies

#1616 Add `ember data` dependency to the quickstart
  blueprints/ember-cli-addon-docs/index.js
  tests/dummy/app/templates/docs/quickstart.md
Labels: documentation
